// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAc9s-5B2kX455up2mYjjVqNkHoUCiToV8',
    appId: '1:72152169100:web:4204f4453174af997659a9',
    messagingSenderId: '72152169100',
    projectId: 'bloodbridge-bb5ce',
    authDomain: 'bloodbridge-bb5ce.firebaseapp.com',
    storageBucket: 'bloodbridge-bb5ce.firebasestorage.app',
    measurementId: 'G-MRGS87C0LD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbklUq4tD1vK3cHFI-WAEMnvVrpqSuLgc',
    appId: '1:72152169100:android:1d5ad7863abfdd1b7659a9',
    messagingSenderId: '72152169100',
    projectId: 'bloodbridge-bb5ce',
    storageBucket: 'bloodbridge-bb5ce.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzXAC8A1Lyyto2hOT-3H9PjQWcTMx28y4',
    appId: '1:72152169100:ios:054b6794397671f47659a9',
    messagingSenderId: '72152169100',
    projectId: 'bloodbridge-bb5ce',
    storageBucket: 'bloodbridge-bb5ce.firebasestorage.app',
    iosBundleId: 'com.example.bloodBridge',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAzXAC8A1Lyyto2hOT-3H9PjQWcTMx28y4',
    appId: '1:72152169100:ios:054b6794397671f47659a9',
    messagingSenderId: '72152169100',
    projectId: 'bloodbridge-bb5ce',
    storageBucket: 'bloodbridge-bb5ce.firebasestorage.app',
    iosBundleId: 'com.example.bloodBridge',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAc9s-5B2kX455up2mYjjVqNkHoUCiToV8',
    appId: '1:72152169100:web:85622617bae7c3907659a9',
    messagingSenderId: '72152169100',
    projectId: 'bloodbridge-bb5ce',
    authDomain: 'bloodbridge-bb5ce.firebaseapp.com',
    storageBucket: 'bloodbridge-bb5ce.firebasestorage.app',
    measurementId: 'G-2XMRC315TB',
  );
}
